
modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="etb"
version="${file.jarVersion}"
displayName="Eternal Blocks"
logoFile="etb.png"

credits="Thanks to Jayzet for the Eternal Biomes"
authors="Ricy40, Oopster & Jayzet"

description='''
A Mod to add blocks for the Eternal mod biomes using open terrain generator.
'''

[[dependencies.etb]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.etb]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
